name: gpucpp-ci

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: No-op Step
      run: echo "This is a no-op action"

    - name: Install CMake
      run: sudo apt-get install cmake

    - name: Build project
      run: make all
